language: node_js
sudo: false
node_js:
  - "0.10"
services:
  - mongodb
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
script: meteor --settings private/config/development.json
