language: node_js
sudo: false
node_js:
  - "0.10"
services:
  - mongodb
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - npm install velocity -g
before_script:
  - export METEOR_ENV="development"
script: velocity test-app --ci --settings private/config/development.example.json
