language: node_js
sudo: false
node_js:
  - "0.10"
services:
  - mongodb
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
before_script:
  - "chmod ugo+x scripts/run-tests.sh"
  - export METEOR_ENV="development"
script: ./travis.sh
